src/cafeShop/routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Auth::routes();
//Route::resource('/admin', 'BackendController');

Route::get('/admin/danhsachmonan/print', 'Backend\MonAnController@prints')->name('danhsachmonan.print');
Route::get('/admin/danhsachmonan/excel', 'Backend\MonAnController@excel')->name('danhsachmonan.excel');
Route::get('/admin/danhsachmonan/pdf', 'Backend\MonAnController@pdf')->name('danhsachmonan.pdf');
Route::resource('/admin/danhsachmonan', 'Backend\MonAnController');

Route::get('/admin/danhsachcuahang/excel', 'Backend\CuaHangController@excel')->name('danhsachcuahang.excel');
Route::resource('/admin/danhsachcuahang', 'Backend\CuaHangController');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/admin/danhsachloaimonan', 'Backend\LoaiMonAnController');
Route::resource('/admin/danhsachdonvitinh', 'Backend\DonViTinhController');
Route::resource('/admin/danhsachbep', 'Backend\BepController');
Route::resource('/admin/danhsachnhomthucdon', 'Backend\NhomThucDonController');
Route::resource('/admin/danhsachban', 'Backend\BanController');
Route::resource('/admin/danhsachtang', 'Backend\TangController');
Route::resource('/admin/danhsachchucvu', 'Backend\ChucVuController');
Route::resource('/admin/danhsachbophan', 'Backend\BoPhanController');
Route::resource('/admin/danhsachchinhanh', 'Backend\ChiNhanhController');
Route::resource('/admin/danhsachnhanvien', 'Backend\NhanVienController');
Route::resource('/admin/danhsachkho', 'Backend\KhoController');
Route::resource('/admin/danhsachnhomnvl', 'Backend\NhomNVLController');
Route::resource('/admin/danhsachnvl', 'Backend\NguyenVatLieuController');
Route::resource('/admin/danhsachloaictkm', 'Backend\LoaiCTKMController');
Route::resource('/admin/danhsachctkm', 'Backend\ChuongTrinhKhuyenMaiController');

Route::get('/', 'Frontend\FrontendController@index')->name('frontend.home');
Route::get('/gioi-thieu', 'Frontend\FrontendController@about')->name('frontend.about');
Route::get('/lien-he', 'Frontend\FrontendController@contact')->name('frontend.contact');
Route::post('/lien-he/goi-loi-nhan', 'Frontend\FrontendController@sendMailContactForm')->name('frontend.contact.sendMailContactForm');
Route::get('/san-pham', 'Frontend\FrontendController@product')->name('frontend.product');
Route::get('/san-pham/{id}', 'Frontend\FrontendController@productDetail')->name('frontend.productDetail');
Route::get('/gio-hang', 'Frontend\FrontendController@cart')->name('frontend.cart');
Route::post('/dat-hang', 'Frontend\FrontendController@order')->name('frontend.order');
Route::get('/dat-hang/hoan-tat', 'Frontend\FrontendController@orderFinish')->name('frontend.orderFinish');

Route::post('/order/print', 'OrderController@prints')->name('order.print');
Route::post('/order/getHoaDon', 'OrderController@getHoaDon')->name('order.getHoaDon');
Route::resource('/order', 'OrderController');


Route::post('/order/print', 'OrderController@prints')->name('order.print');
Route::post('/order/getHoaDon', 'OrderController@getHoaDon')->name('order.getHoaDon');
Route::resource('/order', 'OrderController');
Route::resource('/admin', 'BackendController');

src/cafeShop/app/MonAn.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MonAn extends Model
{
    protected $table        = 'mst_mon_an';
    protected $fillable     = ['ma_id', 'ma_ten','ma_dienGiai','ma_giaBan','ma_giaVon','ma_mon_dac_trung','ma_thay_doi_theo_thoi_gia','ma_ngung_ban','ma_hinh','id_don_vi_tinh','id_nhom_thuc_don', 'created_at', 'updated_at','deleted_at'];
    protected $primaryKey   = 'ma_id';
    
    public function nhomThucDon() {
        return $this->belongsTo('App\NhomThucDon', 'id_nhom_thuc_don', 'ntd_id');
    }

    public function donViTinh() {
        return $this->belongsTo('App\DonViTinh', 'id_don_vi_tinh', 'dvt_id');
    }

    public function hinhAnh(){
        return $this->hasMany('App\HinhAnh', 'id_mon_an', 'ma_id');
    }
}

src/cafeShop/app/Http/Controllers/Backend/BanController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Ban;
use App\Http\Controllers\Controller;
use App\Tang;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Session;
use function redirect;
use function view;
use Validator;

class BanController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        if(!auth()->user()->can('danhmuc_xem')){
            return view('error.403');
        }
        $ds_ban = Ban::all();
        return view('backend.ban.index')
            ->with('danhsachban', $ds_ban);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        $ds_tang = Tang::all();
        return view('backend.ban.create')
            ->with('danhsachtang', $ds_tang);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'ban_ten' => 'required|min:3|max:100',
            'ban_soLuong' => 'required|numeric',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachban.create'))
                        ->withErrors($validator)
                        ->withInput();
        }
        $b = new Ban();
        $b->ban_ten = $request->ban_ten;
        $b->ban_trangThai = $request->ban_trangThai;
        $b->ban_soLuong = $request->ban_soLuong;
        $b->id_tang = $request->id_tang;
        $b->save();
        Session::flash('alert-info', 'Them moi thanh cong ^^~!!!');
        return redirect()->route('danhsachban.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {  
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $b = Ban::where("ban_id", $id)->first();
        $ds_tang = Tang::all();
        return view('backend.ban.edit')
            ->with('b', $b)
            ->with('danhsachtang', $ds_tang);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'ban_ten' => 'required|min:3|max:100',
            'ban_soLuong' => 'required|numeric',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachban.edit', ['danhsachban' => $id]))
                        ->withErrors($validator)
                        ->withInput();
        }
        $b = Ban::where("ban_id", $id)->first();
        $b->ban_ten = $request->ban_ten;
        $b->ban_trangThai = $request->ban_trangThai;
        $b->ban_soLuong = $request->ban_soLuong;
        $b->id_tang = $request->id_tang;
        $b->save();
        Session::flash('alert-info', 'Cập nhật thành công ^^~!!!');
        return redirect()->route('danhsachban.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        if(!auth()->user()->can('danhmuc_xoa')){
            return view('error.403');
        }
        $b = Ban::where("ban_id", $id)->first();
        $$b->delete();
        Session::flash('alert-info', 'Xóa bàn thành công ^^~!!!');
        return redirect()->route('danhsachban.index');
    }
}

src/cafeShop/app/Http/Controllers/Backend/BepController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Bep;
use Validator;


class BepController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!auth()->user()->can('danhmuc_xem')){
            return view('error.403');
        }
        $ds_loai = Bep::all();
        return view('backend.bep.index')
                ->with('danhsachbep',$ds_loai);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        return view('backend.bep.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'b_ten' => 'required|min:3|max:50',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachbep.create'))
                        ->withErrors($validator)
                        ->withInput();
        }
        $b = new Bep();
        $b->b_ten = $request->b_ten;
        $b->save();
        Session::flash('alert-info', 'Them moi thanh cong ^^~!!!');
        return redirect()->route('danhsachbep.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $b = Bep::where("b_id",  $id)->first();
        return view('backend.bep.edit')
            ->with('b', $b);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'b_ten' => 'required|min:3|max:50',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachbep.edit', ['danhsachbep' => $id]))
                        ->withErrors($validator)
                        ->withInput();
        }
        $b = Bep::where("b_id",  $id)->first();
        $b->b_ten = $request->b_ten;
        $b->save();
        Session::flash('alert-info', 'Cập nhật thành công ^^~!!!');
        return redirect()->route('danhsachbep.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!auth()->user()->can('danhmuc_xoa')){
            return view('error.403');
        }
        $b = Bep::where("b_id",  $id)->first();
        $b->delete();
        Session::flash('alert-info', 'Xóa sản phẩm thành công ^^~!!!');
        return redirect()->route('danhsachbep.index');
    }
}

src/cafeShop/app/Http/Controllers/Backend/BoPhanController.php
<?php

namespace App\Http\Controllers\Backend;

use App\BoPhan;
use App\Http\Controllers\Controller;
use Validator;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Session;
use function redirect;
use function route;
use function view;

class BoPhanController extends Controller
{
    
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        if(!auth()->user()->can('danhmuc_xem')){
            return view('error.403');
        }
        $ds_bp = BoPhan::all();
        return view('backend.bophan.index')
                ->with('danhsachbophan',$ds_bp);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        return view('backend.bophan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'bp_ten' => 'required|min:3|max:50',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachbophan.create'))
                        ->withErrors($validator)
                        ->withInput();
        }
        $bp = new BoPhan();
        $bp->bp_ten = $request->bp_ten;
        $bp->save();
        Session::flash('alert-info', 'Them moi thanh cong ^^~!!!');
        return redirect()->route('danhsachbophan.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $bp = BoPhan::where("bp_id",  $id)->first();
        return view('backend.bophan.edit')
            ->with('bp', $bp);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'bp_ten' => 'required|min:3|max:50',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachbophan.edit', ['danhsachbophan' => $id]))
                        ->withErrors($validator)
                        ->withInput();
        }
        $bp = BoPhan::where("bp_id",  $id)->first();
        $bp->bp_ten = $request->bp_ten;
        $bp->save();
        Session::flash('alert-info', 'Cập nhật thanh cong ^^~!!!');
        return redirect()->route('danhsachbophan.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        if(!auth()->user()->can('danhmuc_xoa')){
            return view('error.403');
        }
        $bp = BoPhan::where("bp_id",  $id)->first();
        $bp->delete();
        Session::flash('alert-info', 'Xóa bộ phận thành công ^^~!!!');
        return redirect()->route('danhsachbophan.index');
    }
}

src/cafeShop/app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BackendController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

src/cafeShop/resources/views/backend/monan/create.blade.php
@extends('backend.layouts.master')

@section('title')
Thêm mới món ăn
@endsection

@section('custom-css')
<!-- Các css dành cho thư viện bootstrap-fileinput -->
<link href="{{ asset('vendor/bootstrap-fileinput/css/fileinput.css') }}" media="all" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
<link href="{{ asset('vendor/bootstrap-fileinput/themes/explorer-fas/theme.css') }}" media="all" rel="stylesheet" type="text/css"/>
<style>
    .form-control{
        width:500px;
    }
</style>
@endsection

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<h1>Danh Sách Món Ăn</h1>
<br>
<form method="post" action="{{ route('danhsachmonan.store') }}" enctype="multipart/form-data">
    <button type="button" class="btn btn-success" onclick=history.back() >Quay lại</button>
    <button type="submit" class="btn btn-primary">Lưu</button>
    <br><br>
    {{ csrf_field() }}
    <div class="form-group">
        <label for="">Nhóm thực đơn</label>
        <select name="id_nhom_thuc_don" class="form-control">
            @foreach($danhsachntd as $ntd)
                @if(old('id_nhom_thuc_don') == $ntd->ntd_id)
                <option value="{{ $ntd->ntd_id }}" selected>{{ $ntd->ntd_ten }}</option>
                @else
                <option value="{{ $ntd->ntd_id }}">{{ $ntd->ntd_ten }}</option>
                @endif
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <label for="">Nhóm thực đơn</label>
        <select name="id_don_vi_tinh" class="form-control">
            @foreach($danhsachdvt as $dvt)
                @if(old('id_nhom_thuc_don') == $dvt->dvt_id)
                <option value="{{ $dvt->dvt_id }}" selected>{{ $dvt->dvt_ten }}</option>
                @else
                <option value="{{ $dvt->dvt_id }}">{{ $dvt->dvt_ten }}</option>
                @endif
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <label for="ma_ten">Tên món ăn</label>
        <input type="text" class="form-control" id="ma_ten" name="ma_ten" value="{{ old('ma_ten') }}">
    </div>
    <div class="form-group">
        <label for="ma_dienGiai">Diễn giải</label>
        <textarea rows="5" cols="20" class="form-control" id="ma_dienGiai" name="ma_dienGiai" value="{{ old('ma_dienGiai') }}"></textarea>
    </div>

    <div class="form-group">
        <label for="ma_giaBan">Giá bán</label>
        <input type="text" class="form-control" id="ma_giaBan" name="ma_giaBan" value="{{ old('ma_giaBan') }}">
    </div>
    <div class="form-group">
        <label for="ma_giaVon">Giá vốn</label>
        <input type="text" class="form-control" id="ma_giaVon" name="ma_giaVon" value="{{ old('ma_giaVon') }}">
    </div>
    <div class="form-group">
        <label for="ma_mon_dac_trung">Món đặc trưng</label>
        <select name="ma_mon_dac_trung" class="form-control">
            <option value="1" {{old('ma_mon_dac_trung') == 1 ? "selected" : "" }}>Đặc trưng</option>
            <option value="2" {{old('ma_mon_dac_trung') == 2 ? "selected" : "" }}>Không đặc trưng</option>
        </select>
    </div>
    <div class="form-group">
        <label for="ma_thay_doi_theo_thoi_gia">Thay đổi theo thời giá</label>
        <select name="ma_thay_doi_theo_thoi_gia" class="form-control">
            <option value="1" {{old('ma_thay_doi_theo_thoi_gia') == 1 ? "selected" : "" }}>Không</option>
            <option value="2" {{old('ma_thay_doi_theo_thoi_gia') == 2 ? "selected" : "" }}>Có</option>
        </select>
    </div>
    <div class="form-group">
        <label for="ma_ngung_ban">Ngừng bán</label>
        <select name=" ma_ngung_ban" class="form-control">
            <option value="1" {{old('ma_ngung_ban') == 1 ? "selected" : "" }}>Không</option>
            <option value="2" {{old('ma_ngung_ban') == 2 ? "selected" : "" }}>Có</option>
        </select>
    </div>
    <div class="form-group">
         <label>Hình đại diện</label>
        <div class="file-loading">
            <input id="ma_hinh" type="file" name="ma_hinh" value="{{ old('ma_hinh') }}">
        </div>
    </div>
    <div class="form-group">
        <label>Hình ảnh liên quan sản phẩm</label>
        <div class="file-loading"> 
            <input id="ma_hinhanhlienquan" type="file" name="ma_hinhanhlienquan[]" multiple value="{{ old('ma_hinhanhlienquan') }}">
        </div>
    </div>
    <button type="button" class="btn btn-success" onclick=history.back() >Quay lại</button>
    <button type="submit" class="btn btn-primary">Lưu</button>
</form>
@endsection

@section('custom-scripts')
<!-- Các script dành cho thư viện bootstrap-fileinput -->
<script src="{{ asset('vendor/bootstrap-fileinput/js/plugins/sortable.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/js/fileinput.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/js/locales/fr.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/themes/fas/theme.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/themes/explorer-fas/theme.js') }}" type="text/javascript"></script>

<script>
    $(document).ready(function() {
        $("#ma_hinh").fileinput({
            theme: 'fas',
            showUpload: false,
            showCaption: false,
            browseClass: "btn btn-primary btn-lg",
            fileType: "any",
            previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
            overwriteInitial: false
        });

        $("#ma_hinhanhlienquan").fileinput({
            theme: 'fas',
            showUpload: false,
            showCaption: false,
            browseClass: "btn btn-primary btn-lg",
            fileType: "any",
            previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
            overwriteInitial: false,
            allowedFileExtensions: ["jpg", "gif", "png", "txt"]
        });
    });
</script>

<!-- Các script dành cho thư viện Mặt nạ nhập liệu InputMask -->
<script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.js') }}"></script>
<script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.date.extensions.js') }}"></script>
<script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.extensions.js') }}"></script>

<script>
$(document).ready(function(){
    
});
</script>

@endsection

src/cafeShop/resources/views/backend/monan/index.blade.php
@extends('backend.layouts.master')

@section('title')
Danh sách Món Ăn
@endsection
@section('custom-css')
<style>
    a{
        margin-bottom: 10px;
    }
    th, td{
        text-align: center;
    }
</style>
@endsection
@section('content')
<div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
      @if(Session::has('alert-' . $msg))
      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
      @endif
    @endforeach
</div>

<h1>Danh Sách Món Ăn</h1>
<br>
<a href="{{ route('danhsachmonan.create') }}" class="btn btn-primary" title="Thêm mới">+</a>
<a href="{{ route('danhsachmonan.print') }}" class="btn btn-primary">In ấn</a>
<a href="{{ route('danhsachmonan.excel') }}" class="btn btn-primary">Xuất Excel</a>
<a href="{{ route('danhsachmonan.pdf') }}" class="btn btn-primary">Xuất PDF</a>

<table class="table table-bordered table-striped">
    <thead class="thead-dark">
        <tr>
            <th>STT</th>
            <th>Tên</th>
            <th>Giá bán</th>
            <th>Hình ảnh</th>
            <th>Đơn vị tính</th>
            <th>Nhóm thực đơn</th>
            <th>Thao tác</th>
        </tr>
    </thead>
    <tbody>
        <?php $stt = 1;?>
        @foreach ($danhsachmonan as $ma)
            <tr>
                <td width='5%'>{{ $stt }}</td>
                <td width='10%'>{{ $ma->ma_ten}}</td>
                <td>{{ number_format($ma->ma_giaBan)}}đ</td>
                <td width='20%'><img width='100px' height="80px" src="{{ asset('storage/photos/' .  $ma->ma_hinh ) }}" class="img-list" /></td>
                <td width='10%'>{{ $ma->donViTinh->dvt_ten}}</td>
                <td width='10%'>{{ $ma->nhomThucDon->ntd_ten}}</td>
                <td>
                    <a href="{{ route('danhsachmonan.edit', ['danhsachmonan' => $ma->ma_id]) }}" class="btn btn-primary pull-left" title="Chỉnh sửa">Sửa</i></a>
                    <a href="{{ route('danhsachmonan.show', ['danhsachmonan' => $ma->ma_id]) }}" class="btn btn-primary pull-left" title="Chi tiết">Chi tiết</i></a>
                    <form method="post" action="{{ route('danhsachmonan.destroy', ['danhsachmonan' => $ma->ma_id]) }}" class="pull-left">
                        <input type="hidden" name="_method" value="DELETE" />
                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-danger" title="Xóa">Xóa</button>
                    </form>
                </td>
            </tr>
            <?php $stt ++;?>
        @endforeach
    
    </tbody>
</table>
@endsection

@section('custom-scripts')

@endsection