src/cafeShop/routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Auth::routes();
//Route::resource('/admin', 'BackendController');

Route::get('/admin/danhsachmonan/print', 'Backend\MonAnController@prints')->name('danhsachmonan.print');
Route::get('/admin/danhsachmonan/excel', 'Backend\MonAnController@excel')->name('danhsachmonan.excel');
Route::get('/admin/danhsachmonan/pdf', 'Backend\MonAnController@pdf')->name('danhsachmonan.pdf');
Route::resource('/admin/danhsachmonan', 'Backend\MonAnController');

Route::get('/admin/danhsachcuahang/excel', 'Backend\CuaHangController@excel')->name('danhsachcuahang.excel');
Route::resource('/admin/danhsachcuahang', 'Backend\CuaHangController');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/admin/danhsachloaimonan', 'Backend\LoaiMonAnController');
Route::resource('/admin/danhsachdonvitinh', 'Backend\DonViTinhController');
Route::resource('/admin/danhsachbep', 'Backend\BepController');
Route::resource('/admin/danhsachnhomthucdon', 'Backend\NhomThucDonController');
Route::resource('/admin/danhsachban', 'Backend\BanController');
Route::resource('/admin/danhsachtang', 'Backend\TangController');
Route::resource('/admin/danhsachchucvu', 'Backend\ChucVuController');
Route::resource('/admin/danhsachbophan', 'Backend\BoPhanController');
Route::resource('/admin/danhsachchinhanh', 'Backend\ChiNhanhController');
Route::resource('/admin/danhsachnhanvien', 'Backend\NhanVienController');
Route::resource('/admin/danhsachkho', 'Backend\KhoController');
Route::resource('/admin/danhsachnhomnvl', 'Backend\NhomNVLController');
Route::resource('/admin/danhsachnvl', 'Backend\NguyenVatLieuController');
Route::resource('/admin/danhsachloaictkm', 'Backend\LoaiCTKMController');
Route::resource('/admin/danhsachctkm', 'Backend\ChuongTrinhKhuyenMaiController');

Route::get('/', 'Frontend\FrontendController@index')->name('frontend.home');
Route::get('/gioi-thieu', 'Frontend\FrontendController@about')->name('frontend.about');
Route::get('/lien-he', 'Frontend\FrontendController@contact')->name('frontend.contact');
Route::post('/lien-he/goi-loi-nhan', 'Frontend\FrontendController@sendMailContactForm')->name('frontend.contact.sendMailContactForm');
Route::get('/san-pham', 'Frontend\FrontendController@product')->name('frontend.product');
Route::get('/san-pham/{id}', 'Frontend\FrontendController@productDetail')->name('frontend.productDetail');
Route::get('/gio-hang', 'Frontend\FrontendController@cart')->name('frontend.cart');
Route::post('/dat-hang', 'Frontend\FrontendController@order')->name('frontend.order');
Route::get('/dat-hang/hoan-tat', 'Frontend\FrontendController@orderFinish')->name('frontend.orderFinish');

Route::post('/order/print', 'OrderController@prints')->name('order.print');
Route::post('/order/getHoaDon', 'OrderController@getHoaDon')->name('order.getHoaDon');
Route::resource('/order', 'OrderController');


Route::post('/order/print', 'OrderController@prints')->name('order.print');
Route::post('/order/getHoaDon', 'OrderController@getHoaDon')->name('order.getHoaDon');
Route::resource('/order', 'OrderController');
Route::resource('/admin', 'BackendController');

src/cafeShop/app/CuaHang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CuaHang extends Model
{
    protected $table        = 'mst_cua_hang';
    protected $fillable     = ['ch_id', 'ch_ten','ch_tenNguoiDaiDien','ch_diaChi','ch_soDienThoai','ch_maSoThue', 'created_at', 'updated_at','deleted_at'];
    protected $primaryKey   = 'ch_id';
}

src/cafeShop/app/Http/Controllers/Backend/BanController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Ban;
use App\Http\Controllers\Controller;
use App\Tang;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Session;
use function redirect;
use function view;
use Validator;

class BanController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        if(!auth()->user()->can('danhmuc_xem')){
            return view('error.403');
        }
        $ds_ban = Ban::all();
        return view('backend.ban.index')
            ->with('danhsachban', $ds_ban);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        $ds_tang = Tang::all();
        return view('backend.ban.create')
            ->with('danhsachtang', $ds_tang);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'ban_ten' => 'required|min:3|max:100',
            'ban_soLuong' => 'required|numeric',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachban.create'))
                        ->withErrors($validator)
                        ->withInput();
        }
        $b = new Ban();
        $b->ban_ten = $request->ban_ten;
        $b->ban_trangThai = $request->ban_trangThai;
        $b->ban_soLuong = $request->ban_soLuong;
        $b->id_tang = $request->id_tang;
        $b->save();
        Session::flash('alert-info', 'Them moi thanh cong ^^~!!!');
        return redirect()->route('danhsachban.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {  
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $b = Ban::where("ban_id", $id)->first();
        $ds_tang = Tang::all();
        return view('backend.ban.edit')
            ->with('b', $b)
            ->with('danhsachtang', $ds_tang);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'ban_ten' => 'required|min:3|max:100',
            'ban_soLuong' => 'required|numeric',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachban.edit', ['danhsachban' => $id]))
                        ->withErrors($validator)
                        ->withInput();
        }
        $b = Ban::where("ban_id", $id)->first();
        $b->ban_ten = $request->ban_ten;
        $b->ban_trangThai = $request->ban_trangThai;
        $b->ban_soLuong = $request->ban_soLuong;
        $b->id_tang = $request->id_tang;
        $b->save();
        Session::flash('alert-info', 'Cập nhật thành công ^^~!!!');
        return redirect()->route('danhsachban.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        if(!auth()->user()->can('danhmuc_xoa')){
            return view('error.403');
        }
        $b = Ban::where("ban_id", $id)->first();
        $$b->delete();
        Session::flash('alert-info', 'Xóa bàn thành công ^^~!!!');
        return redirect()->route('danhsachban.index');
    }
}

src/cafeShop/app/Http/Controllers/Backend/BepController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Bep;
use Validator;


class BepController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!auth()->user()->can('danhmuc_xem')){
            return view('error.403');
        }
        $ds_loai = Bep::all();
        return view('backend.bep.index')
                ->with('danhsachbep',$ds_loai);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        return view('backend.bep.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'b_ten' => 'required|min:3|max:50',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachbep.create'))
                        ->withErrors($validator)
                        ->withInput();
        }
        $b = new Bep();
        $b->b_ten = $request->b_ten;
        $b->save();
        Session::flash('alert-info', 'Them moi thanh cong ^^~!!!');
        return redirect()->route('danhsachbep.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $b = Bep::where("b_id",  $id)->first();
        return view('backend.bep.edit')
            ->with('b', $b);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'b_ten' => 'required|min:3|max:50',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachbep.edit', ['danhsachbep' => $id]))
                        ->withErrors($validator)
                        ->withInput();
        }
        $b = Bep::where("b_id",  $id)->first();
        $b->b_ten = $request->b_ten;
        $b->save();
        Session::flash('alert-info', 'Cập nhật thành công ^^~!!!');
        return redirect()->route('danhsachbep.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!auth()->user()->can('danhmuc_xoa')){
            return view('error.403');
        }
        $b = Bep::where("b_id",  $id)->first();
        $b->delete();
        Session::flash('alert-info', 'Xóa sản phẩm thành công ^^~!!!');
        return redirect()->route('danhsachbep.index');
    }
}

src/cafeShop/app/Http/Controllers/Backend/BoPhanController.php
<?php

namespace App\Http\Controllers\Backend;

use App\BoPhan;
use App\Http\Controllers\Controller;
use Validator;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Session;
use function redirect;
use function route;
use function view;

class BoPhanController extends Controller
{
    
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        if(!auth()->user()->can('danhmuc_xem')){
            return view('error.403');
        }
        $ds_bp = BoPhan::all();
        return view('backend.bophan.index')
                ->with('danhsachbophan',$ds_bp);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        return view('backend.bophan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        if(!auth()->user()->can('danhmuc_them')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'bp_ten' => 'required|min:3|max:50',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachbophan.create'))
                        ->withErrors($validator)
                        ->withInput();
        }
        $bp = new BoPhan();
        $bp->bp_ten = $request->bp_ten;
        $bp->save();
        Session::flash('alert-info', 'Them moi thanh cong ^^~!!!');
        return redirect()->route('danhsachbophan.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $bp = BoPhan::where("bp_id",  $id)->first();
        return view('backend.bophan.edit')
            ->with('bp', $bp);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        if(!auth()->user()->can('danhmuc_sua')){
            return view('error.403');
        }
        $validator = Validator::make($request->all(), [
            'bp_ten' => 'required|min:3|max:50',
        ]);
        if ($validator->fails()) {
            return redirect(route('danhsachbophan.edit', ['danhsachbophan' => $id]))
                        ->withErrors($validator)
                        ->withInput();
        }
        $bp = BoPhan::where("bp_id",  $id)->first();
        $bp->bp_ten = $request->bp_ten;
        $bp->save();
        Session::flash('alert-info', 'Cập nhật thanh cong ^^~!!!');
        return redirect()->route('danhsachbophan.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        if(!auth()->user()->can('danhmuc_xoa')){
            return view('error.403');
        }
        $bp = BoPhan::where("bp_id",  $id)->first();
        $bp->delete();
        Session::flash('alert-info', 'Xóa bộ phận thành công ^^~!!!');
        return redirect()->route('danhsachbophan.index');
    }
}

src/cafeShop/app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BackendController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

src/cafeShop/resources/views/backend/cuahang/create.blade.php
@extends('backend.layouts.master')

@section('title')
Thêm mới cửa hàng
@endsection

@section('custom-css')
<style>
    .form-control{
        width:500px;
    }
</style>
@endsection

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<h1>Thêm mới cửa hàng</h1>
<br>

<form method="post" action="{{ route('danhsachcuahang.store') }}" enctype="multipart/form-data">
    {{ csrf_field() }}
    <div class="form-group">
        <label for="ch_ten">Tên cửa hàng</label>
        <input type="text" class="form-control" id="ch_ten" name="ch_ten" value="{{ old('ch_ten') }}">
    </div>
    <div class="form-group">
        <label for="ch_tenNguoiDaiDien">Tên người đại diện</label>
        <input type="text" class="form-control" id="ch_tenNguoiDaiDien" name="ch_tenNguoiDaiDien" value="{{ old('ch_tenNguoiDaiDien') }}">
    </div>
    <div class="form-group">
        <label for="ch_diaChi">Địa chỉ</label>
        <input type="text" class="form-control" id="ch_diaChi" name="ch_diaChi" value="{{ old('ch_diaChi') }}">
    </div><div class="form-group">
        <label for="ch_soDienThoai">Số điện thoại</label>
        <input type="text" class="form-control" id="ch_soDienThoai" name="ch_soDienThoai" value="{{ old('ch_soDienThoai') }}">
    </div>
    <div class="form-group">
        <label for="ch_maSoThue">Mã số thuế</label>
        <input type="text" class="form-control" id="ch_maSoThue" name="ch_maSoThue" value="{{ old('ch_maSoThue') }}">
    </div>
    
    <button type="button" class="btn btn-success" onclick=history.back() >Quay lại</button>
    <button type="submit" class="btn btn-primary">Lưu</button>
</form>
@endsection

@section('custom-scripts')
<script>
$(document).ready(function(){
    
});
</script>

@endsection

src/cafeShop/resources/views/backend/cuahang/edit.blade.php
@extends('backend.layouts.master')

@section('title')
Hiệu chỉnh cửa hàng
@endsection

@section('custom-css')
<style>
    .form-control{
        width:500px;
    }
</style>
@endsection

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<h1>Hiệu chỉnh cửa hàng</h1>
<form method="post" action="{{ route('danhsachcuahang.update', ['danhsachcuahang' => $ch->ch_id]) }}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="PUT" />
    {{ csrf_field() }}
    <div class="form-group">
        <label for="ch_ten">Tên cửa hàng</label>
        <input type="text" class="form-control" id="ch_ten" name="ch_ten" value="{{ old('ch_ten', $ch->ch_ten) }}">
    </div>
    <div class="form-group">
        <label for="ch_tenNguoiDaiDien">Tên người đại diện</label>
        <input type="text" class="form-control" id="ch_tenNguoiDaiDien" name="ch_tenNguoiDaiDien" value="{{ old('ch_tenNguoiDaiDien', $ch->ch_tenNguoiDaiDien) }}">
    </div>
    <div class="form-group">
        <label for="ch_diaChi">Địa chỉ</label>
        <input type="text" class="form-control" id="ch_diaChi" name="ch_diaChi" value="{{ old('ch_diaChi', $ch->ch_diaChi) }}">
    </div><div class="form-group">
        <label for="ch_soDienThoai">Số điện thoại</label>
        <input type="text" class="form-control" id="ch_soDienThoai" name="ch_soDienThoai" value="{{ old('ch_soDienThoai', $ch->ch_soDienThoai) }}">
    </div>
    <div class="form-group">
        <label for="ch_maSoThue">Mã số thuế</label>
        <input type="text" class="form-control" id="ch_maSoThue" name="ch_maSoThue" value="{{ old('ch_maSoThue', $ch->ch_maSoThue) }}">
    </div>
    <button type="submit" class="btn btn-primary">Lưu</button>
    <button type="button" class="btn btn-success" onclick=history.back() >Quay lại</button>
</form>
@endsection

@section('custom-scripts')
<script>
$(document).ready(function(){
    
});
</script>

@endsection

src/cafeShop/resources/views/backend/cuahang/index.blade.php
@extends('backend.layouts.master')

@section('title')
Danh sách cửa hàng
@endsection
@section('custom-css')
<style>
    a{
        margin-bottom: 10px;
    }
    th, td{
        text-align: center;
    }
</style>
@endsection
@section('content')
<div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
      @if(Session::has('alert-' . $msg))
      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
      @endif
    @endforeach
</div>

<h1>Danh Sách cửa hàng</h1>
<br>
<a href="{{ route('danhsachcuahang.create') }}" class="btn btn-primary">+</a>

<table class="table table-bordered table-striped">
    <thead class="thead-dark">
        <tr>
            <th>STT</th>
            <th>Tên cửa hàng</th>
            <th>Tên người đại diện</th>
            <th>Địa chỉ</th>
            <th>Số điện thoại</th>
            <th>Mã số thuế</th>
            <th>Thao tác</th>
        </tr>
    </thead>
    <tbody>
        <?php $stt = 1;?>
        @foreach ($danhsachcuahang as $ch)
            <tr>
                <td width='10%'>{{ $stt}}</td>
                <td>{{ $ch->ch_ten}}</td>
                <td>{{ $ch->ch_tenNguoiDaiDien}}</td>
                <td>{{ $ch->ch_diaChi}}</td>
                <td>{{ $ch->ch_soDienThoai}}</td>
                <td>{{ $ch->ch_maSoThue}}</td>
                <td>
                    <a href="{{ route('danhsachcuahang.edit', ['danhsachcuahang' => $ch->ch_id]) }}" class="btn btn-primary pull-left">Sửa</a>
                    <form method="post" action="{{ route('danhsachcuahang.destroy', ['danhsachcuahang' => $ch->ch_id]) }}" class="pull-left">
                        <input type="hidden" name="_method" value="DELETE" />
                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-danger">Xóa</button>
                    </form>
                </td>
            </tr>
            <?php $stt ++;?>
        @endforeach
    
    </tbody>
</table>
@endsection

@section('custom-scripts')

@endsection